---

- name: Initializing cluster...
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --cri-socket=/var/run/crio/crio.sock >> cluster_init.log
  args:
    chdir: $HOME
    creates: cluster_init.log

- name: Pulling remote cluster configuration...
  fetch: 
    src: /etc/kubernetes/admin.conf
    dest: "{{ kubeconfig | default('./kube.conf') }}"
    flat: yes

- name: Removing taint from master (only) node...
  command: kubectl taint nodes --all node-role.kubernetes.io/master-