---

# - name: Initialize cluster...
#   command: kubeadm init --pod-network-cidr=10.244.0.0/16 --cri-socket=/var/run/crio/crio.sock
- name: Initializing cluster...
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --cri-socket=/var/run/crio/crio.sock >> cluster_intialized.txt
  args:
    chdir: $HOME
    creates: cluster_intialized.txt

- name: Creating Kubernetes home directory...
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Copying config to ~/.kube/config...
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes

- name: Removing taint from master (only) node...
  command: kubectl taint nodes --all node-role.kubernetes.io/master-